### ISSUE TITLE
Missing dependency googletrans

### ISSUE THREAD

**Issue by rffontenelle** [zcribe/translate-po#1]
Instructions on [README](https://pypi.org/project/translate-po/) are to import from "translate_po", but this command returns:

```
>>> from translate_po.main import run
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rffontenelle/.local/lib/python3.8/site-packages/translate_po/main.py", line 5, in <module>
    from googletrans import Translator
ModuleNotFoundError: No module named 'googletrans'
```

[googletrans](https://pypi.org/project/googletrans/) should be a dependency, or at least the user should be informed to install it.

**Comment by zcribe** [comment]
Fixed
1205a84b5bf465c65efe1798ce0809c7dacd70c1
